# live model config data for the FACET2E model

name: FACET2E

dirs:
    lattice: /usr/local/facet/tools/facet2-lattice/
    model_data: /u1/facet/physics/F2_live_model/
    server_logs: /u1/facet/physics/F2_live_model/logs

# common string formats for presenting dates/timestamps
dt_fmt: "%Y-%m-%d %H:%M:%S"
ts_fmt: "%Y%m%d%H%M%S"

server:
    # time in s to wait between server loops
    poll_interval: 1.0
    PV:
        heartbeat: 'PHYS:SYS1:1:MODEL_SERVER'
        provider_stem: 'BMAD:SYS0:1'
    logs:
        level: INFO
        N_backup: 10
        max_MB: 10
        fmt: "%(asctime)s.%(msecs)03d [F2ModelServer] %(levelname)s: %(message)s "


bmad:
    # beamline element Bmad received particle dumps from injector sims
    PTC_treaty_elem: L0AFEND

    # time in s to wait between calls to daemon thread functions
    poll_interval: 0.1

    # absolute filepath for the tao.init to hand to PyTao
    tao_init_path: /usr/local/facet/tools/facet2-lattice/bmad/models/f2_elec/tao.init

    logs:
        fmt: "%(asctime)s.%(msecs)03d [BmadLiveModel] %(levelname)s: %(message)s "

# linac description
# L0 - L3 start/end element names are for LEM
linac:
    regions: [L0, L1, L2, L3]
    L0:
        e_start: L0AF
        e_end: ENDDL10
        knames: [L0*F]
        matching_quads: [QA10361, QA10371, QE10425, QE10441, QE10511, QE10525]
    L1:
        
        e_start: BEGL1F
        e_end: ENDBC11_2
        knames: [K11_1*, K11_2*]
        matching_quads: [QM11358, QM11362, QM11393, Q11401]
    L2:
        e_start: BEGL2F
        e_end: ENDBC14_2
        knames: [K11_4*, K11_5*, K11_6*, K11_7*, K11_8*, K12_*, K13_*, K14_*]
        matching_quads: []
    L3:
        e_start: BEGL2F
        e_end: ENDBC14_2
        knames: [K15_*, K16_*, K17_*, K18_*, K19_*]
        matching_quads: []

    # these klystrons are gone or are *way* offline
    bad_klys: [K11_3, K14_7, K15_2, K19_7, K19_8]
